const SHEETS = {
  funnel: "Funnel",
  leads: "Leads",
  deals: "Deals",
  handoff: "Handoff",
  weeklyMetrics: "Weekly Metrics",
  events: "Events",
  config: "Config"
};

const SCHEMAS = {
  [SHEETS.funnel]: [
    "Stage",
    "Count",
    "Stale Count",
    "Needs Attention",
    "Recommended Action",
    "Last Updated"
  ],
  [SHEETS.leads]: [
    "Lead ID",
    "Entity Key",
    "Company",
    "Company Domain",
    "First Name",
    "Last Name",
    "Email",
    "Source",
    "Campaign",
    "Lead Stage",
    "Owner",
    "Smartlead Campaign ID",
    "Smartlead Lead ID",
    "Last Reply At",
    "Reply Summary",
    "Notes",
    "Next Step",
    "Slack Thread",
    "Created At",
    "Updated At",
    "Source Event ID"
  ],
  [SHEETS.deals]: [
    "Deal ID",
    "Entity Key",
    "Company",
    "Company Domain",
    "First Name",
    "Last Name",
    "Email",
    "Source",
    "Campaign",
    "Deal Stage",
    "Owner",
    "Call Date",
    "Call Status",
    "Fathom URL",
    "Fathom Recording ID",
    "Pricing",
    "Hours/Week",
    "Engineer Type",
    "Skills Needed",
    "Project Scope",
    "Start Date",
    "Close Date",
    "If Lost Reason",
    "Next Steps",
    "Notes",
    "Slack Thread",
    "Handoff Status",
    "Created At",
    "Updated At",
    "Source Event ID"
  ],
  [SHEETS.handoff]: [
    "Handoff ID",
    "Deal ID",
    "Entity Key",
    "Company",
    "Client/Contact",
    "Email",
    "Owner",
    "Handoff Stage",
    "Trigger Stage",
    "Engineer Type",
    "Skills Needed",
    "Hours/Week",
    "Start Date",
    "Pricing",
    "Project Description",
    "Candidate/Profile Requirements",
    "Call Notes",
    "Next Steps",
    "Slack Handoff Link",
    "Created At",
    "Updated At"
  ],
  [SHEETS.weeklyMetrics]: [
    "Metric ID",
    "Week Start",
    "Campaign ID",
    "Campaign",
    "Campaign Status",
    "Sent",
    "Opened",
    "Replied",
    "Positive Replies",
    "Calls Booked",
    "Deals Created",
    "Input Calls",
    "Contract Signed",
    "Open Rate",
    "Reply Rate",
    "Positive Reply Rate",
    "Booking Rate",
    "Diagnosis",
    "Last Synced At"
  ],
  [SHEETS.events]: [
    "Event ID",
    "Source",
    "Event Type",
    "Entity Key",
    "Received At",
    "Processed At",
    "Status",
    "Summary",
    "Raw Payload"
  ],
  [SHEETS.config]: [
    "Type",
    "Key",
    "Value",
    "Slack User ID",
    "Notes"
  ]
};

const CONFIG_ROWS = [
  ["lead_stage", "Positive Response", "Positive Response", "", "Replied with interest"],
  ["lead_stage", "In Conversation", "In Conversation", "", "Active back-and-forth"],
  ["lead_stage", "Call Booked", "Call Booked", "", "Graduates to Deals"],
  ["lead_stage", "Not Now / Nurture", "Not Now / Nurture", "", "Interested later"],
  ["lead_stage", "Unqualified", "Unqualified", "", "Not a fit"],
  ["deal_stage", "Call Booked", "Call Booked", "", "Meeting scheduled"],
  ["deal_stage", "Intro Call", "Intro Call", "", "Initial call happened"],
  ["deal_stage", "Qualified", "Qualified", "", "Real potential"],
  ["deal_stage", "Unqualified", "Unqualified", "", "Not a fit"],
  ["deal_stage", "Considering", "Considering", "", "Interested but undecided"],
  ["deal_stage", "Input Call", "Input Call", "", "Ready for scoping or recruiting handoff"],
  ["deal_stage", "Contract Signed", "Contract Signed", "", "Won and explicit"],
  ["deal_stage", "Cancelled / Lost", "Cancelled / Lost", "", "Not moving forward"],
  ["source", "Outreach", "Outreach", "", ""],
  ["source", "Customer", "Customer", "", ""],
  ["source", "Referral", "Referral", "", ""],
  ["source", "Slack", "Slack", "", "Manual Slack command"],
  ["owner_alias", "Kevin", "Kevin Dubon", "U09HYJ2KD5H", "Operations Systems Architect"],
  ["owner_alias", "Kelvin", "Kelvin", "U0B2CUZKJ9F", "Current sheet assignment value"],
  ["owner_alias", "Jose", "Jose", "U0AKVAXVBB3", "Automation engineer"],
  ["handoff_trigger_stage", "Input Call", "Input Call", "", ""],
  ["handoff_trigger_stage", "Contract Signed", "Contract Signed", "", ""],
  ["slack_channel", "ai-leads", "C0B63R2TC3V", "", "Primary UI channel"]
];

module.exports = { SHEETS, SCHEMAS, CONFIG_ROWS };
