const SHEETS = {
  leads: "Leads",
  deals: "Deals",
  handoff: "Handoff",
  events: "Events",
  config: "Config"
};

const SCHEMAS = {
  [SHEETS.leads]: [
    "Lead ID",
    "Entity Key",
    "Company",
    "Company Domain",
    "First Name",
    "Last Name",
    "Email",
    "Source",
    "Campaign",
    "Lead Stage",
    "Owner",
    "Call Booked On",
    "Notes",
    "Next Step",
    "Created At",
    "Updated At"
  ],
  [SHEETS.deals]: [
    "Deal ID",
    "Entity Key",
    "Company",
    "Company Domain",
    "First Name",
    "Last Name",
    "Email",
    "Source",
    "Campaign",
    "Deal Stage",
    "Owner",
    "Call Had Date",
    "Call Booked On",
    "Call Status",
    "Fathom URL",
    "Pricing",
    "Hours/Week",
    "Engineer Type",
    "Skills Needed",
    "Project Scope",
    "Start Date",
    "Close Date",
    "If Lost Reason",
    "Next Steps",
    "Notes",
    "Handoff Status",
    "Created At",
    "Updated At"
  ],
  [SHEETS.handoff]: [
    "Handoff ID",
    "Deal ID",
    "Entity Key",
    "Company",
    "Send Handoff Recap",
    "Recap Status",
    "Recap Sent At",
    "Recap Error",
    "Client/Contact",
    "Email",
    "Owner",
    "Handoff Stage",
    "Trigger Stage",
    "Engineer Type",
    "Skills Needed",
    "Hours/Week",
    "Start Date",
    "Pricing",
    "Project Description",
    "Candidate/Profile Requirements",
    "Call Notes",
    "Next Steps",
    "Slack Handoff Link",
    "Created At",
    "Updated At"
  ],
  [SHEETS.events]: [
    "Event ID",
    "Source",
    "Event Type",
    "Entity Key",
    "Received At",
    "Processed At",
    "Status",
    "Summary",
    "Raw Payload"
  ],
  [SHEETS.config]: [
    "Type",
    "Key",
    "Value",
    "Slack User ID",
    "Notes"
  ]
};

const CONFIG_ROWS = [
  ["lead_stage", "Replied Positive", "Replied Positive", "", "Replied with interest"],
  ["lead_stage", "Not Interested", "Not Interested", "", "Not a fit or not moving forward"],
  ["lead_stage", "Call Booked", "Call Booked", "", "Graduates to Deals"],
  ["deal_stage", "Cancelled", "Cancelled", "", "Cancelled before/no longer active"],
  ["deal_stage", "Call Booked", "Call Booked", "", "Meeting scheduled"],
  ["deal_stage", "Qualified", "Qualified", "", "Real potential"],
  ["deal_stage", "Unqualified", "Unqualified", "", "Not a fit"],
  ["deal_stage", "Considering", "Considering", "", "Interested but undecided"],
  ["deal_stage", "Input Call", "Input Call", "", "Ready for scoping or recruiting handoff"],
  ["deal_stage", "Contract Signed", "Contract Signed", "", "Won and explicit"],
  ["deal_stage", "Lost", "Lost", "", "Lost after evaluation"],
  ["deal_stage", "Future Need", "Future Need", "", "Interested later"],
  ["source", "Outreach", "Outreach", "", ""],
  ["source", "Customer", "Customer", "", ""],
  ["source", "Referral", "Referral", "", ""],
  ["source", "Slack", "Slack", "", "Manual Slack command"],
  ["source", "Fathom", "Fathom", "", "Call transcript/update"],
  ["source", "Girdley Media", "Girdley Media", "", ""],
  ["owner_alias", "FP", "Franco Pereyra", "", ""],
  ["owner_alias", "CB", "Camila Bagnati", "", ""],
  ["owner_alias", "HC", "Hayden Cohen", "", ""],
  ["owner_alias", "Pedro", "Pedro Vasconcelos", "", ""],
  ["owner_alias", "Nicole", "Nicole Bercovici", "", ""],
  ["owner_alias", "Gianluca", "Gianluca Vendramini", "", ""],
  ["owner_alias", "Kevin", "Kevin Dubon", "U09HYJ2KD5H", "Operations Systems Architect"],
  ["owner_alias", "Kelvin", "Kelvin", "U0B2CUZKJ9F", "Current sheet assignment value"],
  ["owner_alias", "Jose", "Jose", "U0AKVAXVBB3", "Automation engineer"],
  ["handoff_trigger_stage", "Input Call", "Input Call", "", ""],
  ["handoff_trigger_stage", "Contract Signed", "Contract Signed", "", ""],
  ["slack_channel", "ai-leads", "C0B63R2TC3V", "", "Primary UI channel"]
];

module.exports = { SHEETS, SCHEMAS, CONFIG_ROWS };
